# Site settings
url: http://www.anoopjohnson.com
name: Mostly Harmless - Anoop Johnson's Blog
email: blog@anoopjohnson.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anoopjohnson.com" # the base hostname & protocol for your site
twitter_username: anoopjohnson
github_username: anoopj

# Build settings
markdown: kramdown
highlighter: pygments
